JWT_SECRET=InternHubSuperSecretKeyForJWTTokenGeneration2025MustBe256BitsLong
JWT_EXPIRATION=86400000
DATABASE_URL=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12824044?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
DATABASE_USERNAME=sql12824044
DATABASE_PASSWORD=3bLRF4rRcF
upload.dir=uploads/
app.name=InternHub
google.client.id=disabled
google.client.secret=disabled